// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package db

import (
	"context"
	"encoding/json"
)

const insertStation = `-- name: InsertStation :exec
insert into
	stations (
		id,
		name,
		lat,
		lon,
		ebikes_available,
		bike_docks_available,
		ebikes
	)
values (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7
)
ON CONFLICT (id) DO UPDATE
	SET
		name = EXCLUDED.name,
		lat = EXCLUDED.lat,
		lon = EXCLUDED.lon,
		ebikes_available = EXCLUDED.ebikes_available,
		bike_docks_available = EXCLUDED.bike_docks_available,
		ebikes = EXCLUDED.ebikes
`

type InsertStationParams struct {
	ID                 string
	Name               string
	Lat                float64
	Lon                float64
	EbikesAvailable    int32
	BikeDocksAvailable int32
	Ebikes             json.RawMessage
}

// InsertStation inserts citibike station data into the database.
func (q *Queries) InsertStation(ctx context.Context, arg InsertStationParams) error {
	_, err := q.db.ExecContext(ctx, insertStation,
		arg.ID,
		arg.Name,
		arg.Lat,
		arg.Lon,
		arg.EbikesAvailable,
		arg.BikeDocksAvailable,
		arg.Ebikes,
	)
	return err
}
